name: Deploy Symfony
on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SSHPASS: ${{ secrets.APP_PASS }}

    steps:
      - uses: actions/checkout@v2

      - name: APT UPDATE and INSTALL SSHPASS
        run: sudo apt update && sudo apt install sshpass

      - name: deploy
        run:
          sshpass -e ssh -o stricthostkeychecking=no ${{ secrets.APP_USER }}@${{ secrets.APP_HOST }}
          "cd www/ &&
          git pull &&
          php bin/console doctrine:cache:clear-metadata &&
          php bin/console doctrine:cache:clear-query &&
          php bin/console doctrine:cache:clear-result &&
          php bin/console doctrine:migrations:migrate &&
          composer install"
